### ISSUE TITLE
Does the current version only support text but not `markdown` and `html`?

### ISSUE THREAD

**Issue by Now-Sprouting** [ngryman/reading-time#39]
Does the current version only support text but not `markdown` and `html`?

**Comment by Josh-Cena** [comment]
Markdown and HTML work to a certain degree. Since this lib only chops up the prose with `wordBound` and assumes every segment is a word, it's up to the file itself to figure out whether there are space-separated elements that are not words—but seems there aren't many in MD

**Comment by ngryman** [comment]
To answer your question, the current version assumes plain text. Markdown annotations or text-based HTML tags are usually negligible enough so that it doesn't drastically affect the reading time estimation. For the vast majority of use cases, this happens to be good enough.

If the input text contains a lot of HTML markup, for example, I would suggest pre-processing it and strip the tags with a library such as [striptags](https://www.npmjs.com/package/striptags).

I'm closing the issue assuming we answered your question. Happy to re-open if you think there's something we should do in `reading-time`.
