### ISSUE TITLE
Suggestion: Japanese reading-time

### ISSUE THREAD

**Issue by cota-eng** [ngryman/reading-time#52]
Hi, I’m Japanese developer. Japanese is my native language.

If you have some time, please read this issue and respond any comments, suggestions, indicates

## Premise

I already checked PR below.

[https://github.com/ngryman/reading-time/pull/35](https://github.com/ngryman/reading-time/pull/35)

## Background

I want to use this library for Japanese, but cannot use when I see [https://github.com/ngryman/reading-time#help-wanted](https://github.com/ngryman/reading-time#help-wanted)

I want to solve this problem !!

## Main subject

In fact, calculation of Japanese reading-time is below.

```jsx
reading-time [min] = charaters length / 600

ex: こんにちは、お元気ですか？
reading-time [min] = 13 / 600
「、」「。」「？」「！」is not pronounced, but pass time. So count 13 chars
```

So, if I can specify Japanese with some option, this library can calculate Japanese reading-time.

But, this library is used by mainly who uses English.

So, calculation is by word count.

If supply options to function like below, this library can count CJK languages,

```jsx
type LangType = "en" | ... | "ja" | "cn" | "ko"
// cn = china, ko = korea
const stats = readingTime(text,lang="ja");

```

I’m not native of Chinese, Korean, so I don’t know about that truly.

By using Google, I can get a plausible value.

## Additional

By using library below, we can count words.

[https://github.com/leungwensen/tiny-segmenter](https://github.com/leungwensen/tiny-segmenter)

**Comment by Josh-Cena** [comment]
Hi, I'm Chinese, and as you can see from #35, the use-case is primarily focused on parsing CJS characters that don't have wordbounds. The library should currently already be able to output `13` words, right? Our tests already cover this case:

https://github.com/ngryman/reading-time/blob/dbe1d26d14892ee991a1799ca576df4de2824bf7/test/reading-time.spec.ts#L164-L166

The only problem is that some people believe Katakana should not be split by characters, because they represent chunks of foreign words. We currently do exclude Katakana from CJS character range:

https://github.com/ngryman/reading-time/blob/dbe1d26d14892ee991a1799ca576df4de2824bf7/src/reading-time.ts#L23-L37

So my question for you is, what do you think is the word count for this?

https://github.com/ngryman/reading-time/blob/dbe1d26d14892ee991a1799ca576df4de2824bf7/test/reading-time.spec.ts#L168-L171

Is it `7`, as we currently do, or should it be `11`?

**Comment by cota-eng** [comment]
I don't think Katakana should be split...

if the rule `Katakana should be split` is used, "こんにちは世界" is `words: { total: 6 }` .

if Katakana word should be split, Kanji should be split too...

The word '世界' of example sentence "こんにちは世界" is 'world' in English

**Comment by Josh-Cena** [comment]
Kanji is always going to be split, otherwise Chinese can't be handled at all😅 世界 is also "world" in Chinese, so I get what you are saying. I guess it's more consistent if Katakana is split, then.

**Comment by Josh-Cena** [comment]
Yes, if you look at the comment in https://github.com/ngryman/reading-time/pull/35#issuecomment-853364526, you see that the example they gave is `'アメリカ' (America)`, which suffers from the same problem. So is `メガナイト` in the test case I gave above, which translates to `megaknight`, which is one word.

The fundamental problem is that English words are morphemes (units of "meaning"), not phonemes (units of "sound"). I'm not sure which is more significant when counting reading time—for _speaking time_, it's absolutely phonemes, because it would take you more time to pronounce "America" or "megaknight" than "hello"; but if it's _reading_, maybe morphemes are more important? Do you feel like you spend more time reading a mostly Kanji paragraph than a mostly Katakana paragraph that have the same character length?

**Comment by cota-eng** [comment]
> morphemes are more important

I agree

> Do you feel like you spend more time reading a mostly Kanji paragraph than a mostly Katakana paragraph that have the same character length?

I think so too.


---

My solution is to make packages for only Japanese reading time.

Thanks for discussion with me!!
